---
title: "Introduction to UW Hyak"
description: An introduction to using the University of Washington Hyak Cluster
order: 10
---

# Introduction to UW Hyak

[HYAK](https://hyak.uw.edu/systems/) is the University of Washington's high-performance computing cluster:
> HYAK is part of the University of Washington's cyberinfrastructure plan to support world-class research in every department. HYAK is an ecosystem of high-performance compute (HPC) clusters and supporting infrastructure (e.g., data management, computational training, scientific consulting). Acknowleding our Pacific Northwest heritage, HYAK means "fast" in Chinook jargon. Counting 1, 2, and 3 translates to "ikt", "mox", and "klone" in this local trading language. The numbers are cluster names corresponding to the generation of HYAK cluster deployed. We are currently on the 3rd generation cluster for HYAK.


## Klone

The latest generation of the HYAK cluster is Klone.

## Mox

The second generation of the HYAK cluster, Mox, is being phased out in 2024. No new capacity or node additions are planned. The Klone cluster is recommended for all users.

## Resources

Check out UW Research Computing Club's [Slack](https://uw-rcc.slack.com) and ask questions under `hyak-questions`.

For more information, see the official [HYAK website](https://hyak.uw.edu).
